#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    s=0;
    n=int(input())
    p=int((n-1)/3)
    s=((p*(p+1)*3)//2)
    p=int((n-1)/5)
    s=s+((p*(p+1)*5)//2)
    p=int((n-1)/15)
    s=s-((p*(p+1)*15)//2)
    print((s))  

