#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    a=1
    b=1
    s=0
    for i in range(n):
        if(a>=n):
            break
        if(a%2==0):
            s=s+a
        nxt=a
        a=a+b
        b=nxt    
    print(s)    
